# Generated by Django 5.0.1 on 2024-02-07 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Abstract', models.CharField(max_length=50)),
                ('ISBN', models.CharField(max_length=50, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStoreApp.authors')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStoreApp.shelves')),
            ],
        ),
    ]
