version: "3.9"
  
services:  
  django_project:
    build:
        context: ./
        dockerfile: Dockerfile
    # env_file: Project/.env.stage
    ports: 
        - '8099:8099'         
    networks:
        - myAppNetwork 

networks:
    myAppNetwork:
        driver: bridge
 
volumes:
    my_db_vol:
        driver: local